In [10]:
words = '高鐵辦捐血活動 董座江耀宗帶頭挽袖'
seg = jieba.cut(words)
print(" ".join(seg))

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\Wade\AppData\Local\Temp\jieba.cache
Loading model cost 0.768 seconds.
Prefix dict has been built succesfully.


'高鐵辦 捐血 活動   董座 江耀宗 帶頭 挽袖'

### 增加特定詞彙

In [2]:
jieba.load_userdict("user.txt")

### 移除符號(像是冒號與問號)和數字
python regex移除數字

In [5]:
import re
some_text = 'test:123?'
re.sub("\d+|\?|\:", "", some_text)

'test'

---

## 1. 讀取csv並切割字串

In [12]:
import csv
import jieba

strings = []
labels = []

with open('sentences.csv', newline='') as csvfile:
  rows = csv.reader(csvfile)
  for row in rows:
    strings.append(" ".join(jieba.cut(re.sub("\d+|\?|\:|\？|\\r\\n", "", row[0]))))

In [14]:
strings

['高鐵辦 捐血 活動   董座 江耀宗 帶頭 挽袖',
 '高鐵局 ： 延伸 花 億   到 屏東 只 快 分鐘',
 '高鐵 延至 屏東 恐花 億元 、 卻 只 比台 鐵快 分鐘',
 '機 捷通 車   台北 車站 成大迷 宮台 鐵 ： 將改進',
 '高鐵 捐血 傳愛     董事 長 帶頭作 公益',
 '高雄捷 運去 年度 首度 盈餘萬元',
 '桃捷 徵才 逾 萬人 報考     錄取 率僅 %',
 '爭取 高鐵到 屏東   青年 組聯盟 號召 支持',
 '高捷 賺 了     衝運量 兼 擴大勞務',
 '機捷 A 台北 站 轉乘     吉祥物 VR 影片 來 帶路',
 '催淚   視障 女 高鐵站 為 阿母 獻 唱 「 感謝 你 的 愛 」',
 '周一 晨間 列車 自由 座     高鐵 增為 節車 廂',
 '高鐵班 周一 晨間 列車 加開 自由 座   運能 提升',
 '北捷 雞 年 紀念 車票     日開 賣',
 '傳聞 多   桃 市府 日 公布 機捷 正式 通車 時間',
 '機捷 何時 通車     桃捷 日 宣布',
 '機捷 可望 元宵 通車   桃捷 ： 尚未 取得 營運許 可 \u3000',
 '機捷 履勘 改善 完成     交部將 發營 運許 可',
 '三鐵共站 動線 不 友善     議員促 左營 站 改善',
 '二二八 連假 高鐵 加班 車     日 凌晨 賣',
 '高鐵 周年   外籍 顧問 自發 揪 團回 台灣',
 '高鐵連假 加班 車   周六 開放 訂票',
 '機場 捷運營 運許 可及 通車 時間     日 公布',
 '張 花冠 宣布   日起 至 元宵 節兩條 電動 公車 路線 免費 搭',
 '機場 捷運何 時通 鄭文燦 ： 今年 月初',
 '機捷 試營運 方案   下午 A 站 說 明細節',
 '記者 團試 乘 機捷 直達車   實測 到 機場 時間 是 ...',
 '機捷試 乘遇 地震     減速 慢行 秒',
 '桃園 機場 捷運 ／ 試營運   ／ 正式 通車',
 '機捷 / 起試 營運個 月   / 正式 營運',
 '機捷 試營運 / 預辦 登機   限時 後 航班',
 '機捷 免費試 乘團 體限站   自由 行全線 進出',
 '機 捷通 車成 真 

#### Tokenize

In [15]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(2000)
tokenizer.fit_on_texts(strings)

Using TensorFlow backend.


### text to numbers

In [16]:
string_sequences = tokenizer.texts_to_sequences(strings)
string_sequences

[[220, 124, 221, 222, 223, 224, 225],
 [27, 2, 125, 226, 126, 15, 80, 127, 81, 51],
 [8, 227, 80, 228, 229, 28, 230, 127, 231, 232, 51],
 [16, 17, 9, 18, 233, 234, 235, 128, 2, 236],
 [8, 124, 237, 238, 129, 239, 240],
 [241, 242, 243, 244, 245],
 [6, 246, 130, 39, 247, 248, 249],
 [250, 251, 80, 252, 253, 254, 255],
 [29, 256, 52, 257, 258, 259],
 [1, 20, 18, 3, 82, 260, 261, 262, 131, 263],
 [264, 265, 266, 132, 83, 267, 268, 269, 30, 270, 271, 133, 272, 31],
 [134, 135, 53, 5, 54, 8, 273, 274, 136],
 [275, 134, 135, 53, 84, 5, 54, 276, 137],
 [55, 277, 85, 138, 56, 278, 139],
 [279, 280, 281, 140, 7, 86, 1, 21, 11, 57],
 [1, 282, 11, 6, 7, 141],
 [1, 283, 58, 11, 6, 2, 284, 285, 286, 142, 287],
 [1, 288, 59, 40, 289, 290, 143, 142],
 [291, 292, 41, 293, 294, 144, 3, 59],
 [60, 42, 8, 43, 9, 7, 145, 139],
 [8, 295, 296, 297, 298, 299, 300, 32],
 [301, 43, 9, 146, 22, 302],
 [12, 303, 143, 304, 11, 57, 7, 86],
 [147, 305, 141, 306, 87, 58, 307, 308, 309, 148, 13, 23],
 [12, 310, 311, 

## 2. 讀取切好字的csv

In [1]:
import numpy as np
import pandas as pd

DF = pd.read_csv('title1-8_final.csv')
DF.head()

Title                          Title_CKIP Category
0   捷運間隔5分鐘放人進站　人潮塞爆國父紀念館站     捷運　間隔　5分鐘　放　人　進站　人潮　塞爆　國父　紀念館　站        t
1    高捷延至兩點收班　夢時代跨年人潮1小時散去      高捷　延至　兩　點收　班　夢時代　跨年　人潮　1　小時　散去        t
2  31日北捷運量226.7萬人　比前年少40萬人  31　日　北　捷運　量　226.7　萬　人　比　前　年少　40萬　人        t
3   北捷跨年輸運減少38萬人次　是因假日沒上班族     北捷　跨年　輸運　減少　38萬　人次　是　因　假日　沒　上班族        t
4        元旦連假收尾　高鐵烏日站午後湧人潮             元旦　連假　收尾　高鐵　烏日站　午後　湧　人潮        t

In [20]:
DF.isnull().sum()

Title         1
Title_CKIP    1
Category      1
dtype: int64

Drop整row na

In [2]:
DF.dropna(axis=0, inplace=True)

In [3]:
segement = DF['Title_CKIP'].copy()
segement = segement.astype(str)
label = DF['Category'].copy()

#### label做one hot

In [4]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# le = LabelEncoder()
# label_le = le.fit_transform(label)

one_hot = OneHotEncoder()
label_ohe = one_hot.fit_transform(DF[['Category']])
label_ohe_array = label_ohe.toarray()
print(label_ohe_array)
print(one_hot.get_feature_names())

[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
['x0_e' 'x0_o' 'x0_s' 'x0_t']


In [38]:
segement.values[0]

'捷運\u3000間隔\u30005分鐘\u3000放\u3000人\u3000進站\u3000人潮\u3000塞爆\u3000國父\u3000紀念館\u3000站'

**將\u3000以空格取代**

In [5]:
import re
for index in range(segement.size):
    segement.values[index] = re.sub("\\u3000", " ", segement.values[index])

In [43]:
segement.values[0]

'捷運 間隔 5分鐘 放 人 進站 人潮 塞爆 國父 紀念館 站'

#### Tokenize and to numbers

In [6]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(5000)
tokenizer.fit_on_texts(segement.values)
string_sequences = tokenizer.texts_to_sequences(segement.values)

Using TensorFlow backend.


**截長補短**

In [7]:
from keras.preprocessing import sequence

sequence_padded = sequence.pad_sequences(string_sequences, maxlen=15)
sequence_padded

array([[   0,    0,    0, ..., 1752, 1753,    8],
       [   0,    0,    0, ...,   71,  175, 1755],
       [   0,  761,   44, ..., 1757, 1758,   18],
       ...,
       [   0,    0,    0, ..., 1748, 1749,    8],
       [   0,    0,    0, ..., 1748, 1749,    8],
       [   0,    0,    0, ...,  542,  743,  970]])

In [10]:
sequence_padded.shape

(1452, 15)

**檢查詞頻**

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
cv_result = cv.fit_transform(segement.values)

words = cv.get_feature_names()
# 計算詞頻
frequency = cv_result.toarray().sum(axis=0)

In [17]:
WordDF =  pd.DataFrame(
    {'Words': words,
     'Frequency': frequency
    })

WordDF.sort_values(by=['Frequency'], ascending=False).head(10)

Words  Frequency
3455    高鐵        653
1530    捷運        222
1941    機捷        154
708     北捷        129
677     加開        117
624     列車        112
2283    疏運         74
521     優惠         68
3056    通車         63
1734    旅客         61

### Embedding layer

將數字list轉化為vector list

#### input length由句子長度決定, input dim由字典數決定

### MLP

In [22]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation,Flatten
from keras.layers.embeddings import Embedding

model_MLP = Sequential()

model_MLP.add(Embedding(output_dim=32, input_dim=5000, input_length=15))
model_MLP.add(Dropout(0.2))

model_MLP.add(Flatten())

model_MLP.add(Dense(units=128, activation='relu' ))
model_MLP.add(Dropout(0.4))

model_MLP.add(Dense(units=4, activation='softmax' ))

model_MLP.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 15, 32)            160000    
_________________________________________________________________
dropout_5 (Dropout)          (None, 15, 32)            0         
_________________________________________________________________
flatten_3 (Flatten)          (None, 480)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 128)               61568     
_________________________________________________________________
dropout_6 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_9 (Dense)              (None, 4)                 516       
Total params: 222,084
Trainable params: 222,084
Non-trainable params: 0
_________________________________________________________________


In [25]:
model_MLP.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
train_history_MLP = model_MLP.fit(sequence_padded, label_ohe,batch_size=50, epochs=40,verbose=2, validation_split=0.2)

Train on 1160 samples, validate on 291 samples
Epoch 1/40
 - 0s - loss: 0.0026 - acc: 0.9983 - val_loss: 2.6041 - val_acc: 0.5979
Epoch 2/40
 - 0s - loss: 0.0030 - acc: 0.9974 - val_loss: 2.6197 - val_acc: 0.5945
Epoch 3/40
 - 0s - loss: 0.0023 - acc: 0.9983 - val_loss: 2.6701 - val_acc: 0.5911
Epoch 4/40
 - 0s - loss: 0.0028 - acc: 0.9974 - val_loss: 2.7507 - val_acc: 0.5945
Epoch 5/40
 - 0s - loss: 0.0033 - acc: 0.9983 - val_loss: 2.7814 - val_acc: 0.5945
Epoch 6/40
 - 0s - loss: 0.0030 - acc: 0.9991 - val_loss: 2.7724 - val_acc: 0.5979
Epoch 7/40
 - 0s - loss: 0.0032 - acc: 0.9974 - val_loss: 2.7256 - val_acc: 0.5979
Epoch 8/40
 - 0s - loss: 0.0021 - acc: 0.9983 - val_loss: 2.7563 - val_acc: 0.5911
Epoch 9/40
 - 0s - loss: 0.0029 - acc: 0.9991 - val_loss: 2.8068 - val_acc: 0.5911
Epoch 10/40
 - 0s - loss: 0.0037 - acc: 0.9966 - val_loss: 2.7423 - val_acc: 0.6014
Epoch 11/40
 - 0s - loss: 0.0025 - acc: 0.9974 - val_loss: 2.7207 - val_acc: 0.5979
Epoch 12/40
 - 0s - loss: 0.0027 - acc

### RNN

### LSTM

In [28]:
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation,Flatten
from keras.layers.embeddings import Embedding
from keras.layers import Bidirectional, CuDNNLSTM

model_LSTM = Sequential()

model_LSTM.add(Embedding(output_dim=128, input_dim=5000, input_length=15))
model_LSTM.add(Dropout(0.4))

model_LSTM.add(CuDNNLSTM(32, return_sequences=True))
model_LSTM.add(CuDNNLSTM(32, return_sequences=True))
model_LSTM.add(CuDNNLSTM(32, return_sequences=False))

model_LSTM.add(Dense(units=50, activation='relu' ))
model_LSTM.add(Dropout(0.4))
model_LSTM.add(Dense(units=4, activation='softmax' ))

model_LSTM.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 15, 128)           640000    
_________________________________________________________________
dropout_9 (Dropout)          (None, 15, 128)           0         
_________________________________________________________________
cu_dnnlstm_3 (CuDNNLSTM)     (None, 15, 32)            20736     
_________________________________________________________________
cu_dnnlstm_4 (CuDNNLSTM)     (None, 15, 32)            8448      
_________________________________________________________________
cu_dnnlstm_5 (CuDNNLSTM)     (None, 32)                8448      
_________________________________________________________________
dense_12 (Dense)             (None, 50)                1650      
_________________________________________________________________
dropout_10 (Dropout)         (None, 50)                0         
__________

**有做one hot的label就不能用loss = sparse_categorical_crossentropy**

> https://stackoverflow.com/questions/49392972/error-when-checking-target-expected-dense-3-to-have-shape-3-but-got-array-wi

In [30]:
model_LSTM.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
train_history_LSTM = model_LSTM.fit(sequence_padded, label_ohe, batch_size=100, epochs=30, verbose=2, validation_split=0.2)

Train on 1160 samples, validate on 291 samples
Epoch 1/30
 - 1s - loss: 0.0121 - acc: 0.9974 - val_loss: 2.8684 - val_acc: 0.5945
Epoch 2/30
 - 0s - loss: 0.0095 - acc: 0.9974 - val_loss: 2.8206 - val_acc: 0.5979
Epoch 3/30
 - 0s - loss: 0.0095 - acc: 0.9974 - val_loss: 3.0308 - val_acc: 0.5945
Epoch 4/30
 - 0s - loss: 0.0081 - acc: 0.9974 - val_loss: 3.4984 - val_acc: 0.5979
Epoch 5/30
 - 0s - loss: 0.0068 - acc: 0.9974 - val_loss: 3.0688 - val_acc: 0.5773
Epoch 6/30
 - 0s - loss: 0.0058 - acc: 0.9974 - val_loss: 3.0980 - val_acc: 0.5773
Epoch 7/30
 - 0s - loss: 0.0045 - acc: 0.9974 - val_loss: 3.2512 - val_acc: 0.5911
Epoch 8/30
 - 0s - loss: 0.0043 - acc: 0.9983 - val_loss: 3.3558 - val_acc: 0.5876
Epoch 9/30
 - 0s - loss: 0.0057 - acc: 0.9983 - val_loss: 3.4013 - val_acc: 0.6082
Epoch 10/30
 - 0s - loss: 0.0052 - acc: 0.9974 - val_loss: 3.5947 - val_acc: 0.6014
Epoch 11/30
 - 0s - loss: 0.0062 - acc: 0.9983 - val_loss: 3.4107 - val_acc: 0.5876
Epoch 12/30
 - 0s - loss: 0.0039 - acc